
document.write('<link href="~/Scripts/FlowChart/resources/css/jquery-ui-themes.css" type="text/css" rel="stylesheet" />')
document.write('<link href="~/Scripts/FlowChart/resources/css/axure_rp_page.css" type="text/css" rel="stylesheet" />')
document.write('<link href="~/Scripts/FlowChart/data/styles.css" type="text/css" rel="stylesheet" />')
document.write('<link href="~/Scripts/FlowChart/files/基本条件核查/styles.css" type="text/css" rel="stylesheet" />')
document.write('<script src="~/Scripts/FlowChart/resources/scripts/jquery-ui-1.8.10.custom.min.js"></script>')
document.write('<script src="~/Scripts/FlowChart/resources/scripts/axure/axQuery.js"></script>')
document.write('<script src="~/Scripts/FlowChart/resources/scripts/axure/globals.js"></script>')
document.write('<script src="~/Scripts/FlowChart/resources/scripts/axutils.js"></script>')
document.write('<script src="~/Scripts/FlowChart/resources/scripts/axure/annotation.js"></script>')
document.write('<script src="~/Scripts/FlowChart/resources/scripts/axure/axQuery.std.js"></script>')
document.write('<script src="~/Scripts/FlowChart/resources/scripts/axure/doc.js"></script>')
document.write('<script src="~/Scripts/FlowChart/data/document.js"></script>')
document.write('<script src="~/Scripts/FlowChart/resources/scripts/messagecenter.js"></script>')
document.write('<script src="~/Scripts/FlowChart/resources/scripts/axure/events.js"></script>')
document.write('<script src="~/Scripts/FlowChart/resources/scripts/axure/action.js"></script>')
document.write('<script src="~/Scripts/FlowChart/resources/scripts/axure/expr.js"></script>')
document.write('<script src="~/Scripts/FlowChart/resources/scripts/axure/geometry.js"></script>')
document.write('<script src="~/Scripts/FlowChart/resources/scripts/axure/flyout.js"></script>')
document.write('<script src="~/Scripts/FlowChart/resources/scripts/axure/ie.js"></script>')
document.write('<script src="~/Scripts/FlowChart/resources/scripts/axure/model.js"></script>')
document.write('<script src="~/Scripts/FlowChart/resources/scripts/axure/repeater.js"></script>')
document.write('<script src="~/Scripts/FlowChart/resources/scripts/axure/sto.js"></script>')
document.write('<script src="~/Scripts/FlowChart/resources/scripts/axure/utils.temp.js"></script>')
document.write('<script src="~/Scripts/FlowChart/resources/scripts/axure/variables.js"></script>')
document.write('<script src="~/Scripts/FlowChart/resources/scripts/axure/drag.js"></script>')
document.write('<script src="~/Scripts/FlowChart/resources/scripts/axure/move.js"></script>')
document.write('<script src="~/Scripts/FlowChart/resources/scripts/axure/visibility.js"></script>')
document.write('<script src="~/Scripts/FlowChart/resources/scripts/axure/style.js"></script>')
document.write('<script src="~/Scripts/FlowChart/resources/scripts/axure/adaptive.js"></script>')
document.write('<script src="~/Scripts/FlowChart/resources/scripts/axure/tree.js"></script>')
document.write('<script src="~/Scripts/FlowChart/resources/scripts/axure/init.temp.js"></script>')
document.write('<script src="~/Scripts/FlowChart/files/基本条件核查/data.js"></script>')
document.write('<script src="~/Scripts/FlowChart/resources/scripts/axure/legacy.js"></script>')
document.write('<script src="~/Scripts/FlowChart/resources/scripts/axure/viewer.js"></script>')